config/routes.rb
Rails.application.routes.draw do

  match 'stories/new' => 'stories#new', via: [:get, :post]
  match 'stories/start' => 'stories#start', via: [:get, :post]

  match 'stories/:id/places' => 'stories#story_places_list', via: [:get]
  match 'stories/:id/places/map' => 'stories#story_places_map', via: [:get], as: 'story_places_map'
  match 'places/:id/map' => 'places#place_map', via: [:get], as: 'place_map'
  match '/my_stories' => 'usersavedstories#my_stories', via: [:get, :post]
  match '/my_storiesandplaces' => 'usersavedstories#my_storiesandplaces', via: [:get, :post]
  match '/usersavedstories/:id' => 'usersavedstories#destroy', via: [:delete], as: :destroy_usersavedstories
  match '/my_savedplaces' => 'usersavedplaces#index', via: [:get, :post]
  match '/story/save_story_show/:id' => 'stories#save_story_show', via: [:get, :post], as: :save_story_show
  match '/story/forget_story_show/:id' => 'stories#forget_story_show', via: [:get, :post], as: :forget_story_show

  post '/visitors/save_story/:id', to: 'visitors#save_story', as: :save_story
  post '/visitors/forget_story/:id', to: 'visitors#forget_story', as: :forget_story

  match 'visitors/index' => 'visitors#index', via: [:get]

  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :hoteljunks
  resources :locations
  resources :slocations
  resources :splace_categories
  resources :story_categories
  resources :places
  resources :stories
  resources :map, only: [:index] do
    collection do
      get 'all_nearby_places'
    end
  end

end

app/controllers/hoteljunks_controller.rb
class HoteljunksController < ApplicationController
  before_action :set_hoteljunk, only: [:show, :edit, :update, :destroy]

  # GET /hoteljunks
  # GET /hoteljunks.json
  def index
    @hoteljunks = Hoteljunk.all
  end

  # GET /hoteljunks/1
  # GET /hoteljunks/1.json
  def show
  end

  # GET /hoteljunks/new
  def new
    @hoteljunk = Hoteljunk.new
  end

  # GET /hoteljunks/1/edit
  def edit
  end

  # POST /hoteljunks
  # POST /hoteljunks.json
  def create
    @hoteljunk = Hoteljunk.new(hoteljunk_params)

    respond_to do |format|
      if @hoteljunk.save
        format.html { redirect_to @hoteljunk, notice: 'Hoteljunk was successfully created.' }
        format.json { render :show, status: :created, location: @hoteljunk }
      else
        format.html { render :new }
        format.json { render json: @hoteljunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoteljunks/1
  # PATCH/PUT /hoteljunks/1.json
  def update
    respond_to do |format|
      if @hoteljunk.update(hoteljunk_params)
        format.html { redirect_to @hoteljunk, notice: 'Hoteljunk was successfully updated.' }
        format.json { render :show, status: :ok, location: @hoteljunk }
      else
        format.html { render :edit }
        format.json { render json: @hoteljunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoteljunks/1
  # DELETE /hoteljunks/1.json
  def destroy
    @hoteljunk.destroy
    respond_to do |format|
      format.html { redirect_to hoteljunks_url, notice: 'Hoteljunk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoteljunk
      @hoteljunk = Hoteljunk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hoteljunk_params
      params.require(:hoteljunk).permit(:name)
    end
end

app/helpers/hoteljunks_helper.rb
module HoteljunksHelper
end

app/views/hoteljunks/_form.html.erb
<%= form_for(@hoteljunk) do |f| %>
  <% if @hoteljunk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hoteljunk.errors.count, "error") %> prohibited this hoteljunk from being saved:</h2>

      <ul>
      <% @hoteljunk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hoteljunks/edit.html.erb
<h1>Editing Hoteljunk</h1>

<%= render 'form' %>

<%= link_to 'Show', @hoteljunk %> |
<%= link_to 'Back', hoteljunks_path %>

app/views/hoteljunks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hoteljunks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hoteljunks.each do |hoteljunk| %>
      <tr>
        <td><%= hoteljunk.name %></td>
        <td><%= link_to 'Show', hoteljunk %></td>
        <td><%= link_to 'Edit', edit_hoteljunk_path(hoteljunk) %></td>
        <td><%= link_to 'Destroy', hoteljunk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoteljunk', new_hoteljunk_path %>

app/views/hoteljunks/new.html.erb
<h1>New Hoteljunk</h1>

<%= render 'form' %>

<%= link_to 'Back', hoteljunks_path %>

app/views/hoteljunks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hoteljunk.name %>
</p>

<%= link_to 'Edit', edit_hoteljunk_path(@hoteljunk) %> |
<%= link_to 'Back', hoteljunks_path %>