config/routes.rb
Rails.application.routes.draw do

  match 'stories/new' => 'stories#new', via: [:get, :post]
  match 'stories/start' => 'stories#start', via: [:get, :post]

  match 'stories/:id/places' => 'stories#story_places_list', via: [:get]
  match 'stories/:id/places/map' => 'stories#story_places_map', via: [:get], as: 'story_places_map'
  match 'places/:id/map' => 'places#place_map', via: [:get], as: 'place_map'
  match '/my_stories' => 'usersavedstories#my_stories', via: [:get, :post]
  match '/my_storiesandplaces' => 'usersavedstories#my_storiesandplaces', via: [:get, :post]
  match '/usersavedstories/:id' => 'usersavedstories#destroy', via: [:delete], as: :destroy_usersavedstories
  match '/my_savedplaces' => 'usersavedplaces#index', via: [:get, :post]
  match '/story/save_story_show/:id' => 'stories#save_story_show', via: [:get, :post], as: :save_story_show
  match '/story/forget_story_show/:id' => 'stories#forget_story_show', via: [:get, :post], as: :forget_story_show

  post '/visitors/save_story/:id', to: 'visitors#save_story', as: :save_story
  post '/visitors/forget_story/:id', to: 'visitors#forget_story', as: :forget_story

  match 'visitors/index' => 'visitors#index', via: [:get]

  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :hoteljunks
  resources :locations
  resources :slocations
  resources :splace_categories
  resources :story_categories
  resources :places
  resources :stories
  resources :map, only: [:index] do
    collection do
      get 'all_nearby_places'
    end
  end

end

app/models/story.rb
class Story < ActiveRecord::Base

  validates :editor_tagline, :presence => { :message => "EDITOR TAGLINE is required" }
  validates :description, :presence => { :message => "DESCRIPTION is required" }
  validates :title, :presence => { :message => "TITLE is required" }

  attr_accessor :slocation_ids, :splace_category_ids, :story_category_ids

  # TODO: no validations!

  # these next 4 relationships are temporary bridges until places are fully implemented
  has_many :story_slocation_joins, dependent: :destroy
  has_many :slocations, through: :story_slocation_joins
  accepts_nested_attributes_for :slocations
  has_many :story_splace_joins, dependent: :destroy
  has_many :splace_categories, through: :story_splace_joins
  accepts_nested_attributes_for :splace_categories

  has_many :urls, as: :urlable, dependent: :destroy
  accepts_nested_attributes_for :urls

  has_many :usersavedstories, dependent: :destroy

  has_many :story_place_assignments, dependent: :destroy
  has_many :places, through: :story_place_assignments
  accepts_nested_attributes_for :places,  allow_destroy: true

  has_many :story_category_assignments, dependent: :destroy
  has_many :story_categories, through: :story_category_assignments
  accepts_nested_attributes_for :story_categories

  has_many :author_story_assignments, dependent: :destroy
  has_many :authors, through: :author_story_assignments
  accepts_nested_attributes_for :authors

  has_many :images
  accepts_nested_attributes_for :images, allow_destroy: true

  belongs_to :mediacorp
  accepts_nested_attributes_for :mediacorp

  scope :ready_for_display, -> {where(ready_for_display: true)}

end

app/controllers/stories_controller.rb
require 'domainatrix'
require 'screen_scraper'

class StoriesController < ApplicationController
  before_action :set_story, only: [:edit, :update, :destroy]
  # before_action :set_story, only: [:show, :edit, :update, :destroy]

  def start

  end

  # GET /stories/new
  def new
    # parse the domain
    # @data_entry_begin_time = params[:data_entry_begin_time]
    @source_url_pre = params[:source_url_pre]  #grab user input
    if @source_url_pre.present?
      get_locations_and_categories
      get_domain_info(@source_url_pre)
      @screen_scraper = ScreenScraper.new
      if @screen_scraper.scrape!(@full_web_url)
        @story = Story.new
        @image = @story.images.build
        @image_url = @image.build_url 
        @story_url = @story.urls.build

        # url = @story.urls.build
        # url.images.build
        set_scrape_fields
        # binding.pry
      else
        flash.now.alert = "We can't find that URL – give it another shot"
        render :scrape
      end
    else
      flash.now.alert = "You have to enter a URL for this to work"
      render :scrape
    end
  end

  # POST /stories
  # POST /stories.json
  def create
    # TODO:  check_manual_url(params)
    # binding.pry
    # @story = Story.new(story_params)
    my_params = set_image_params(story_params)
    @story = Story.new(my_params)

    respond_to do |format|
      if @story.save
        update_locations_and_categories(@story, story_params)
        format.html { redirect_to story_path(@story), notice: 'Story was successfully created.' }
        # format.html { redirect_to story_proof_url(@story), notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        @source_url_pre = params["story"]["urls_attributes"]["0"]["full_url"]
        get_domain_info(@source_url_pre)
        set_fields_on_fail(story_params)
        get_locations_and_categories
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    page = params[:page] ? params[:page] : 1
    @stories = Story.paginate(per_page: 50, page: page).order('created_at DESC')
    # @stories = Story.ready_for_display.paginate(per_page: 50, page: page).order('created_at DESC')
    @stories = @stories.where(["title ILIKE ?", "%#{params[:search]}%"]) if params[:search]

  end

  # this show will eventually go away
  def show
    @story = Story.find(params[:id])
    # @story = Story.where(ready_for_display: true).find(params[:id])
    @places = @story.places

    if user_signed_in?
      @saved_story_count = Usersavedstory.where(story_id: @story.id, user_id: current_user.id.to_i).count
      # binding.pry
    end

  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    if @story.update(story_params)
        redirect_to story_path
    else
      render :edit
    end
  end


  def save_story_show
    if user_signed_in?
      user_saved_story = Usersavedstory.new
      user_saved_story.user_id = current_user.id.to_i
      user_saved_story.story_id = params[:id].to_i

      user_saved_story_success = true if user_saved_story.save

      @story = Story.find(params[:id])
      @places_for_this_story = @story.places
      @places_for_this_story.each do |story_places|
        user_saved_place = Usersavedplace.new
        user_saved_place.user_id = current_user.id.to_i
        user_saved_place.usersavedstory_id = Usersavedstory.last.id
        user_saved_place.place_id = story_places.id
        user_saved_place.save
        # binding.pry
      end

      # if user_saved_story_success
      #   render json: {success: true}
      # else
      #   render json: {success: false}
      # end

    redirect_to :back
    # redirect_to '/stories/' + params[:id].to_s
    end
  end

  def forget_story_show
    if user_signed_in?

      user_saved_story = Usersavedstory.where(story_id: params[:id], user_id: current_user.id).first
      user_saved_story.destroy

      redirect_to :back
      # redirect_to '/stories/' + params[:id].to_s
    end
  end

  def story_places_list
    @story = Story.where(ready_for_display: true).find(params[:id])

  end

  def story_places_map
    @story = Story.where(ready_for_display: true).find(params[:id])
    @places = @story.places

    # the hash holds all the markers for the map
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.location.lat
      marker.lng place.location.lng
      name = place.name.present? ? place.name : ''
      marker.infowindow '<a class="iwlayout" href=' + place_path(place) + '>' + name + '</a>'
    end

  end

  private

  def get_domain_info(source_url_pre)

    full_url = Domainatrix.parse(source_url_pre).url
    sub = Domainatrix.parse(source_url_pre).subdomain
    domain = Domainatrix.parse(source_url_pre).domain
    suffix = Domainatrix.parse(source_url_pre).public_suffix
    prefix = (sub == 'www' || sub == '' ? '' : (sub + '.'))
    @base_domain = prefix + domain + '.' + suffix
    # binding.pry

    # d_url = Domainatrix.parse(source_url_pre)
    # @full_domain = d_url.host
    # split_full_domain = @full_domain.split(".")
    # if split_full_domain.length == 2
    #   @base_domain = split_full_domain[0].to_s + "." + split_full_domain[1].to_s
    # else
    #   @base_domain = split_full_domain[1].to_s + "." + split_full_domain[2].to_s
    # end

    # if Mediaowner.where(url_domain: @base_domain).first.present?
    #   @name_display =  Mediaowner.where(url_domain: @base_domain).first.title
    # else
    #   @name_display = 'NO DOMAIN NAME FOUND'
    # end
    @full_web_url = full_url
  end

  def set_scrape_fields
    @title = @screen_scraper.title
    @meta_desc = @screen_scraper.meta_desc
    @meta_keywords = @screen_scraper.meta_keywords
    @meta_type = @screen_scraper.meta_type
    @meta_author = @screen_scraper.meta_author
    @year = @screen_scraper.year
    @month = @screen_scraper.month
    @day = @screen_scraper.day
    @page_imgs = @screen_scraper.page_imgs

    @itemprop_pub_date_match

  end

  def set_fields_on_fail(hash)
    @title = hash['title']['0']
    @meta_desc = hash['description']
    @meta_keywords = hash['urls_attributes']['0']['keywords']
    @meta_tagline = hash["editor_tagline"]
    # @meta_type = hash["story_type"]
    # @meta_author = hash["author"]
    @year = hash["original_published_year"]
    @month = hash["original_published_month"]
    @day = hash["original_published_date"]
    @page_imgs = []
    params['image_src_cache'].try(:each) do |key, src_url|  # in case hidden field hash is nil, added try
      @page_imgs << { 'src_url' => src_url, 'alt_text' => params['image_alt_text_cache'][key] }
    end
    @selected_slocation_ids = process_chosen_params(hash['slocation_ids'])
    @selected_splace_category_ids = process_chosen_params(hash['splace_category_ids'])
    @selected_story_category_ids = process_chosen_params(hash['story_category_ids'])
    # binding.pry
  end

  def set_image_params(story_params)
    image_data = params["story"]["images_attributes"]["0"]["image_data"]
    # image_data = params["story"]["image"]["image_data"]
    # image_data = story_params["urls_attributes"]["0"]["images_attributes"]["0"]["image_data"]
    unless image_data.nil?
      image_data_hash = JSON.parse(image_data)
      @image_url = image_data_hash["src_url"]
      # story_params["urls_attributes"]["0"]["images_attributes"]["0"]["alt_text"]= image_data_hash["alt_text"]
      story_params["images_attributes"]["0"]["image_size_h"] = image_data_hash["image_width"]
      # story_params["urls_attributes"]["0"]["images_attributes"]["0"]["image_width"] = image_data_hash["image_width"]
      story_params["images_attributes"]["0"]["image_size_v"] = image_data_hash["image_height"]
      # story_params["urls_attributes"]["0"]["images_attributes"]["0"]["image_height"]= image_data_hash["image_height"]
    end
    story_params
    # binding.pry
  end

  def get_locations_and_categories
    @slocations = Slocation.order(:name)
    @splace_categories = SplaceCategory.order(:name)
    @story_categories = StoryCategory.order(:name)
  end

  def update_locations_and_categories(story, my_params)
    new_slocations = Slocation.find(process_chosen_params(my_params[:slocation_ids]))
    story.slocations = new_slocations

    new_splace_categories = SplaceCategory.find(process_chosen_params(my_params[:splace_category_ids]))
    story.splace_categories = new_splace_categories

    new_story_categories = StoryCategory.find(process_chosen_params(my_params[:story_category_ids]))
    story.story_categories = new_story_categories
  end

  def process_chosen_params(my_params)
    if my_params.present?
      my_params.reject{|p| p.empty?}.map{|p| p.to_i}
    end
  end

  # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit( :title, :description, :editor_tagline,
              :original_published_year, :original_published_month, :original_published_date,
              :story_slocation_join_ids => [],
              :story_splace_join_ids => [],
              :story_category_ids => [],
              :slocation_ids => [],
              :splace_category_ids => [],
              :story_category_ids => [],
              slocations_attributes: [ :id, :code, :name ],
              splace_categories_attributes: [ :id, :code, :name ],
              story_categories_attributes: [ :id, :code, :name ],
              urls_attributes: [ :id, :full_url, :domain, :keywords],
              places_attributes: [ :id, :name, :email, :phone, :needs_review, :reported_closed, :_destroy,
                     location_attributes: [ :id, :address1, :city, :state, :country, :lat, :lng ]],

app/views/stories/edit_seq.html.erb
<%= form_for @story do |f| %>
  <br>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>
      <ul>
        <% @story.errors.each_with_index do |message, i| %>
          <li><%= message[1] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :urls do |u| %>

    <div class="form-group" style="margin-top: .5%">
    <div class="panel panel-default">
      <div class="panel-body">
        <h1>Edit Publish Sequence</h1><br>
				Sequence:
        <%= f.number_field :release_seq, :value => @sequence, style: "width: 50px; text-align: center"  %>&nbsp;&nbsp;&nbsp;
	      Title:
        <%= u.text_field :url_title, :value => @url_title, :readonly => true, size: 100  %><br>
        <%= hidden_field_tag 'source_action', 'edit_seq' %>
        <%= hidden_field_tag 'old_seq', @sequence %><br>
        <%= f.submit "Re-Sequence", class: 'btn btn-sm btn-success' %>
      </div>
		</div>
	</div>

	<% end %>
<% end %>

app/views/stories/incomplete.html.erb
<h1>Incomplete Stories List</h1>

<table class="table table-condensed">
  <thead>
  <tr>
    <th>ID&nbsp;</th>
    <th>Created&nbsp;</th>
    <th>Title&nbsp;&nbsp;</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @stories.each do |story| %>
    <% story.urls.each do |u| %>
      <tr>
        <td><%= story.id %>&nbsp;</td>
        <td nowrap><%= story.created_at.strftime("%Y-%m-%d %H:%M:%S") %> &nbsp;</td>
         <td><%= u.url_title %>&nbsp;&nbsp;</td>
        <td>&nbsp;&nbsp;<%= link_to 'Show', story %>&nbsp;</td>
        <td><%= link_to 'Edit', edit_story_path(story) %>&nbsp;</td>
        <td><%= link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Scrape New Story', stories_scrape_path %>

app/views/stories/index.html.erb
<div class="panel top-margin-sap" style="padding-bottom: 0px; padding-right: 5px" >
  <p class="search-text" style="font-size: 1.4em; display: inline">Search All Stories</p>&nbsp;&nbsp;
  <p style="font-size: 1.1em; display: inline"> <%= link_to "(or just My Stories)", my_storiesandplaces_path %></p>
  <div class="container left-margin-zero-sap">
    <div class="row" style="padding-top: 5px">
      <%= form_tag nil, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Enter Saved Story Title" %>&nbsp;
        <%= submit_tag 'Search', class: 'btn btn-sm btn-primary' %>
      <% end %>
      <p style="font-size: .8em; line-height: 80%">&nbsp;<%= link_to 'clear search', stories_path %></p>

    </div>
  </div>
</div>

<%= will_paginate @stories %>
<div class="panel">

  <% @stories.each do |story| %>

    <div class="container left-margin-zero-sap">
      <div class="row" style="padding-bottom: 6px">
        <div class="col-xs-5 col-sm-3 col-md-2" style="margin-right: auto;">
	        <% if story.images.first.try(:url) %>
			      <%= link_to image_tag(story.images.first.url.full_url, :width =>2000), story_path(story) %>
					<% else %>
            <%= link_to image_tag("https://goo.gl/0uAmvS", :width =>200), story_path(story) %>
        <% end %>
				</div>

			  <div class="col-sm-9 col-md-6"><hr style="margin-top: 0px; margin-bottom: 1px;">
			    <p  style="font-size: 1.3em; font-family: 'Roboto Condensed'; margin-bottom: 3px"><%= link_to story.title, story_path(story) %></p>
			    <% if story.mediacorp.try(:title) %>
					  <p style="display:inline; font-weight: bold"><%= story.mediacorp.title %></p>&nbsp;&nbsp;&nbsp;
				  <% end %>
			    <% if story.try(:description) %>
					  <p style="display:inline;"><%= story.description.truncate(150, :separator => ' ') %></p>
				  <% else %>
				    <p>(No Description Found)</p><
				  <% end %>
				</div>
			</div>
		</div>
  <% end %>

  <%= will_paginate(@stories) %>
</div>

app/views/stories/new.html.erb
<%= render 'form' %>

app/views/stories/scrape.html.erb
<%= form_tag( :action => "new" ) do %>
  <br><br><br><br>
  <div class="panel panel-default">
    <div class="panel-body">
      <br>
    <table>
      <tr>
        <td><div style="float: left; margin-left: 1px "<%= button_to("Process URL", nil, class: 'btn btn-sm btn-success') %></div></td>
        <td>&nbsp</td>
        <td><%= text_field_tag(:source_url_pre, nil, autofocus: true, :maxlength => 250, :size => 100) %></td>
        <td><%= hidden_field_tag(:data_entry_begin_time, Time.now) %></td>
      </tr>
    </table>
    <br>
  </div></div>

  <%= debug(params) if Rails.env.development? %>
  <%= debug(flash) if Rails.env.development? %>

<% end %>

app/views/stories/sequence.html.erb
<h1>Complete Unpublished Stories List</h1>

<table class="table table-condensed">
  <thead>
  <tr>
    <th>ID&nbsp;</th>
    <th>Created</th>
    <th style="text-align: right">Seq</th>
    <th>&nbsp;&nbsp;Domain&nbsp;&nbsp;</th>
    <th>Locations&nbsp;&nbsp;</th>
    <th>Title&nbsp;&nbsp;</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @stories.each do |story| %>
    <% story.urls.each do |u| %>
      <tr>
        <td><%= story.id %>&nbsp;</td>
        <td nowrap><%= story.created_at.strftime("%Y-%m-%d") %></td>
        <td style="line-height: 1.0; text-align: right"><%= button_to story.release_seq.nil? ? "––" : story.release_seq, edit_seq_path(story), class: 'btn btn-sap btn-info hidden-xs',
                    style: "margin-top: -3px; margin-bottom: -15px" %>&nbsp;</td>
        <td>&nbsp;&nbsp;<%= u.url_domain %></td>
        <td width="10%"><%= story.locations.map { |location| location.code }.join(', ') %>&nbsp;&nbsp;</td>
        <td><%= u.url_title %>&nbsp;&nbsp;</td>
        <td>&nbsp;&nbsp;<%= link_to 'Show', story %>&nbsp;</td>
        <td><%= link_to 'Edit', edit_story_path(story) %>&nbsp;</td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All Stories', stories_path %>

app/views/stories/show.html.erb
<div class="panel top-margin-sap  right-padding-zero-sap" style="font-size: 18px; font-weight: 500">
  <p style="display: inline; margin-bottom: 0px"><%= link_to @story.title, @story.urls.first.full_url, target: '_blank' %>&nbsp;&nbsp;
	  <a href=<%= @story.urls.first.full_url %> target="_blank">
	    <span class="glyphicon glyphicon-globe"></span>
	  </a>
  </p>&nbsp;&nbsp;
  <% if user_signed_in? %>
		<% if @saved_story_count < 1 %>
		  <p style="display: inline; line-height: 1.0"><%= link_to 'Save Story', save_story_show_path(@story.id), class: 'btn btn-success btn-sm' %>&nbsp;</p>
		<% else %>
	    <p style="display: inline; line-height: 1.0"><%= link_to 'Forget Story', forget_story_show_path(@story.id), class: 'btn btn-danger btn-sm' %>&nbsp;</p>
	  <% end %>
	  <% if current_user.admin? %>
		  <p style="display: inline; line-height: 1.0"><%= link_to 'Edit Story', edit_story_path(@story.id), class: 'btn btn-success btn-sm' %>&nbsp;</p>
	  <% end %>
  <% end %>
</div>

<div class="panel  right-padding-zero-sap">
	<div class="container" style="margin-left: -15px">
	  <div class="row" style="padding-bottom: 6px; font-weight: 300">
	    <div class="col-lg-6 col-md-7 col-sm-7 col-xs-12">
	      <strong><%= @story.editor_tagline %></strong>
		    <p style="margin-top: 5px">
		      <% if @story.mediacorp.try(:title) %>
		        <%= @story.mediacorp.title %>.&nbsp;
		      <% end %>
			    <% if @story.try(:description) %>
		        <%= @story.description %>
			    <% else %>
		        <p style="color: #D9D9D9; display: inline">(no description)</p>
			    <% end %>
		    </p>

	      <div class="row" style="margin-top: 10px;padding-bottom: 6px">
	        <div class="col-xs-3 col-sm-2 col-md-2">
	          Author
	        </div>
	        <div class="col-xs-9 col-sm-9 col-md-10">
	          <% if @story.authors.count > 0 %>
	            <ul style="padding-left: 20px;">
	              <% @story.authors.each do |author| %>
	                <li><%= author.first_name %>&nbsp;<%= author.last_name %></li>
	              <% end %>
	            </ul>
	          <% else %>
	            <p style="color: #D9D9D9; display: inline" >(no author)</p>
	          <% end %>
	        </div>
	      </div>

	      <div class="row" style="padding-bottom: 6px">
	        <div class="col-xs-3 col-sm-2 col-md-2">
	          Category
	        </div>
	        <div class="col-xs-9 col-sm-9 col-md-10">
	          <% if @story.story_categories.count > 0 %>
	            <ul style="padding-left: 20px;">
	              <% @story.story_categories.each do |category| %>
	                <li><%= category.name %></li>
	              <% end %>
	            </ul>
	          <% else %>
	            <p style="color: #D9D9D9; display: inline">(no category)</p>
	          <% end %>
	        </div>
	      </div>
	    </div>

	    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-7 img-story-sap"><br>
	      <% if @story.images.first.try(:url) %>
	        <%= link_to image_tag(@story.images.first.url.full_url), @story.urls.first.full_url, target: '_blank' %>
	      <% else %>
	        <%= link_to image_tag("http://media-cdn.tripadvisor.com/media/photo-s/04/26/a1/73/family-restuarant.jpg"), @story.urls.first.full_url, target: '_blank' %>
	      <% end %>
	    </div>

	  </div>
	</div>
</div>

<div class="panel  right-padding-zero-sap">
	<% place_count = @story.places.count %>
  <h4>Explore <%= pluralize(place_count, 'Place') %> in this Story&nbsp;&nbsp;
    <%= link_to "Map View", story_places_map_path(@story), class: 'btn btn-info btn-sm' %></h4>
  <ul style="padding-left: 20px;">
    <% @story.places.each do |place| %>
      <li><%= link_to place.full_name, place_path(place) %></li>
    <% end %>
  </ul>
</div>

<div style="float:left; position:absolute;"><%= link_to 'Back to Stories List', stories_path %></div>

app/views/stories/start.html.erb
<%= form_tag( :action => "new" ) do %>
  <br><br><br><br>
  <div class="panel panel-default">
    <div class="panel-body">

      <div class="col-sm-2 col-md-2 col-lg-1" style="margin-right: auto; margin-top: 10px">
	      <%= button_to "Process URL", class: 'btn btn-sm btn-success' %>
      </div>

      <div class="col-sm-10 col-md-10 col-lg-11" style="margin-right: auto;">
				<%= text_field_tag(:source_url_pre, nil, autofocus: true, class: "form-control") %>
			</div>

			  <!--set timing field-->
		    <%= hidden_field_tag(:data_entry_begin_time, Time.now) %>

    </div>
  </div>

<% end %>

app/views/stories/story_places_list.html.erb
<h2>Places for this Story (most recent first)</h2>

<div class="panel">
  <% @places.each do |place| %>
    <h4><%= link_to place.full_name, place_path(place) %></h4>
	<% end %>
</div>

app/views/stories/story_places_map.html.erb
<h4 class="top-margin-map-sap" >Map for the Places in this Story</h4>

<!--style to fix google map zoom display-->
<style>
	.gm-style img { max-width: none; }
	.gm-style label { width: auto; display: inline; }
</style>

<div class="map_container">
  <div id="map_canvas" class="map_canvas"></div>
</div>

<script type="text/javascript">
//	handler = Gmaps.build('Google');
	handler = Gmaps.build('Google', { markers: { clusterer: {clusterer_gridSize: 60 } } });
	handler.buildMap({
						provider: { maxZoom: 15 },
						internal: {id: 'map_canvas'}
					},
					function(){
						markers = handler.addMarkers(<%=raw @hash.to_json %>);
						handler.bounds.extendWith(markers);
						handler.fitMapToBounds();
					});
</script>