config/routes.rb
Rails.application.routes.draw do

  match 'stories/new' => 'stories#new', via: [:get, :post]
  match 'stories/start' => 'stories#start', via: [:get, :post]

  match 'stories/:id/places' => 'stories#story_places_list', via: [:get]
  match 'stories/:id/places/map' => 'stories#story_places_map', via: [:get], as: 'story_places_map'
  match 'places/:id/map' => 'places#place_map', via: [:get], as: 'place_map'
  match '/my_stories' => 'usersavedstories#my_stories', via: [:get, :post]
  match '/my_storiesandplaces' => 'usersavedstories#my_storiesandplaces', via: [:get, :post]
  match '/usersavedstories/:id' => 'usersavedstories#destroy', via: [:delete], as: :destroy_usersavedstories
  match '/my_savedplaces' => 'usersavedplaces#index', via: [:get, :post]
  match '/story/save_story_show/:id' => 'stories#save_story_show', via: [:get, :post], as: :save_story_show
  match '/story/forget_story_show/:id' => 'stories#forget_story_show', via: [:get, :post], as: :forget_story_show

  post '/visitors/save_story/:id', to: 'visitors#save_story', as: :save_story
  post '/visitors/forget_story/:id', to: 'visitors#forget_story', as: :forget_story

  match 'visitors/index' => 'visitors#index', via: [:get]

  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :hoteljunks
  resources :locations
  resources :slocations
  resources :splace_categories
  resources :story_categories
  resources :places
  resources :stories
  resources :map, only: [:index] do
    collection do
      get 'all_nearby_places'
    end
  end

end

app/controllers/map_controller.rb
class MapController < ApplicationController

  def index
    @favorite_places_json = current_user.favorite_place_coords.to_json
  end

  def index_test

  end

  def show

  end

  def all_nearby_places
    respond_to do |format|
      format.json do
        render json: Location.nearby_places(parse_location_params,50)
      end
    end
  end

  private

  def parse_location_params
    if params[:location_coords_text].present?
      params[:location_coords_text].split(',')
    end
  end

end

app/views/map/all_places.html.erb
<!--style to fix google map zoom display-->
<style>
	.gm-style img { max-width: none; }
	.gm-style label { width: auto; display: inline; }
</style>

<div class="panel top-margin-sap right-padding-zero-sap" >
	<%= link_to 'My Places', my_places_path %> &nbsp;&nbsp;
  <strong>All Places</strong>
</div>

<div id="currentplusfavs" style='width: 100%; height: 800px;'></div>

<script type="text/javascript">

	var handler = Gmaps.build('Google');
	handler.buildMap({
						internal: {id: 'currentplusfavs'}
					},
					function(){
		if(navigator.geolocation)
			navigator.geolocation.getCurrentPosition(displayOnMap);
	});

	function displayOnMap(position){
		var marker = handler.addMarker({  // add current location pin
			lat: position.coords.latitude,
			lng: position.coords.longitude,
			picture: {
				url: "https://sparecube.com/public/img/user-loc-btn.png",
				width:  36,
				height: 36
			}
		});
		// add pins for my save places
		markers = handler.addMarkers(<%=raw @all_places_hash.to_json %>);
		// display map
		handler.map.centerOn(marker);
		handler.getMap().setZoom(10);
//		google.maps.event.trigger(map, "resize");
	};
</script>

app/views/map/index.html.erb
<!--style to fix google map zoom display-->
<style>
	.gm-style img { max-width: none; }
	.gm-style label { width: auto; display: inline; }
</style>

<script type="text/javascript" id="favorite_places_json">
  <%= raw @favorite_places_json %>
</script>

<div class="panel top-margin-sap" style="padding-bottom: 0px; padding-right: 5px" >
  <div class="container left-margin-zero-sap">
    <div class="row" style="padding-top: 5px">
			<div class="col-md-7">
	      <form action="javascript:void(0)" method="GET" class="form-inline map_search_form" data-user-id="1">
	        <div class="form-group" style="display: inline; padding: 2px 0 3px 0">
	          <input type="text" name="search" class="form-control" placeholder="Enter Location" />
	        </div>
					<div class="radio">
					  <label>
					    <input type="radio" name="places_options" value="favorite_places" checked>
					    Favorite Places
					  </label>
					</div>
					<div class="radio">
					  <label>
					    <input type="radio" id="all_places_radio_btn" name="places_options" value="all_places">
					    <span class="text-muted">All Places</span>
					  </label>
					</div>
	        <button type="submit" class="btn btn-info btn-sm" style="margin-top: 5px">Search</button>
	      </form>
			</div>
    </div>
    <div class="search-header">
		</div>
  </div>
</div>

<div class="col-md-offset-3 col-md-5 loading_div">
	<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		Loading Map
	</div>
</div>

<div class="col-md-offset-3 col-md-5 loading_places_div hidden">
	<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		Loading Places
	</div>
</div>

<div class="col-md-12" id="search_map_container_div" data-user-zip-code="<%= current_user.zip_preference %>">
  <div id="map_canvas" style='width: 100%; height: 800px;'></div>
</div>

app/views/map/index_test.html.erb
<div class="panel top-margin-sap" style="padding-bottom: 0px; padding-right: 5px" >
  <p class="search-text" style="font-size: 1.4em; display: inline">Search All Stories</p>&nbsp;&nbsp;
  <p style="font-size: 1.1em; display: inline"> <%= link_to "(or just My Stories)", my_storiesandplaces_path %></p>
  <div class="container left-margin-zero-sap">
    <div class="row" style="padding-top: 5px">
      <%= form_tag nil, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Enter Saved Story Title" %>&nbsp;
        <%= submit_tag 'Search', class: 'btn btn-sm btn-primary' %>
      <% end %>
      <p style="font-size: .8em; line-height: 80%">&nbsp;<%= link_to 'clear search', stories_path %></p>

    </div>
  </div>
</div>

app/views/map/my_places.html.erb
<!--style to fix google map zoom display-->
<style>
	.gm-style img { max-width: none; }
	.gm-style label { width: auto; display: inline; }
</style>

<div class="panel top-margin-sap right-padding-zero-sap" >
  <strong>My Places</strong> &nbsp;&nbsp;
	<%= link_to 'All Places', all_places_path %>
</div>

<div id="currentplusfavs" style='width: 100%; height: 800px;'></div>

<script type="text/javascript">
	var handler = Gmaps.build('Google');
	var providerAtts;
	if(navigator.geolocation){
		navigator.geolocation.getCurrentPosition(function(position){
			var coords = position.coords;
			providerAtts = {
				center:	new google.maps.LatLng(coords.latitude, coords.longitude),
				zoom: 10
			}
			handler.buildMap({
				internal: {id: 'currentplusfavs'},
				provider: providerAtts
			});
		}, function(error){
			// it's possible the user denied access to geolocation even if it is enabled
			providerAtts = {
				center:	new google.maps.LatLng(41.850033, -87.6500523),
				zoom: 5
			}
			handler.buildMap({
				internal: {id: 'currentplusfavs'},
				provider: providerAtts
			});
		});
	}
	else {
		providerAtts = {
			center:	new google.maps.LatLng(41.850033, -87.6500523),
			zoom: 5
		}
		handler.buildMap({
			internal: {id: 'currentplusfavs'},
			provider: providerAtts
		});
	}

	function displayOnMap(){
		var currentLocationMarker = handler.addMarker({  // add current location pin
			lat: position.coords.latitude,
			lng: position.coords.longitude,
			picture: {
				url: "https://sparecube.com/public/img/user-loc-btn.png",
				width:  36,
				height: 36
			}
		});
		// add pins for my save places
		markers = handler.addMarkers(<%=raw @my_places_hash.to_json %>);
		// display map
		handler.map.centerOn(currentLocationMarker);
//		handler.getMap().setZoom(10);
//		google.maps.event.trigger(map, "resize");
	};
</script>

app/views/map/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<%= javascript_include_tag 'application' %>

<div style='width: 800px;'>
  <div id="geolocation" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
	var handler = Gmaps.build('Google');
	handler.buildMap({ internal: {id: 'geolocation'} }, function(){
	if(navigator.geolocation)
	navigator.geolocation.getCurrentPosition(displayOnMap);
	});

	function displayOnMap(position){
	var marker = handler.addMarker({
	lat: position.coords.latitude,
	lng: position.coords.longitude
	});
	handler.map.centerOn(marker);
	};
</script>