config/routes.rb
Rails.application.routes.draw do

  match 'stories/new' => 'stories#new', via: [:get, :post]
  match 'stories/start' => 'stories#start', via: [:get, :post]

  match 'stories/:id/places' => 'stories#story_places_list', via: [:get]
  match 'stories/:id/places/map' => 'stories#story_places_map', via: [:get], as: 'story_places_map'
  match 'places/:id/map' => 'places#place_map', via: [:get], as: 'place_map'
  match '/my_stories' => 'usersavedstories#my_stories', via: [:get, :post]
  match '/my_storiesandplaces' => 'usersavedstories#my_storiesandplaces', via: [:get, :post]
  match '/usersavedstories/:id' => 'usersavedstories#destroy', via: [:delete], as: :destroy_usersavedstories
  match '/my_savedplaces' => 'usersavedplaces#index', via: [:get, :post]
  match '/story/save_story_show/:id' => 'stories#save_story_show', via: [:get, :post], as: :save_story_show
  match '/story/forget_story_show/:id' => 'stories#forget_story_show', via: [:get, :post], as: :forget_story_show

  post '/visitors/save_story/:id', to: 'visitors#save_story', as: :save_story
  post '/visitors/forget_story/:id', to: 'visitors#forget_story', as: :forget_story

  match 'visitors/index' => 'visitors#index', via: [:get]

  root to: 'visitors#index'

  devise_for :users
  resources :users
  resources :hoteljunks
  resources :locations
  resources :slocations
  resources :splace_categories
  resources :story_categories
  resources :places
  resources :stories
  resources :map, only: [:index] do
    collection do
      get 'all_nearby_places'
    end
  end

end

app/models/place.rb
class Place < ActiveRecord::Base

  validates :location_id, presence: true
  validates :reported_closed, inclusion: { in: %w(true false),
                                           message: "%{value} must be 'true' or 'false'" }, :allow_nil => true

  has_many :urls, as: :urlable, dependent: :destroy

  has_many :story_place_assignments, dependent: :destroy
  has_many :stories, through: :story_place_assignments
  accepts_nested_attributes_for :stories

  has_many :place_category_assignments, dependent: :destroy
  has_many :place_categories, through: :place_category_assignments

  has_many :usersavedplaces, dependent: :destroy
  belongs_to :location
  accepts_nested_attributes_for :location

  belongs_to :parent, class_name: 'Place', foreign_key: :parent_id

  def is_parent?
    location_id == 0
  end

  def full_name
    parent_id ? parent_full_name : name
  end

  def is_child?
    parent_id.present?
  end

  def get_parent_categories
    place_categories.map{|pc| pc.get_base_category}
  end

  private

  def parent_full_name
    if parent.name.present? && name.present?
      parent.name + ': ' + name + ' [has parent - this name is parent name + my name]' # obviously temporary
    elsif parent.name.present?
      parent.name + " [using parent's name - i have no name]" # obviously temporary
    else
      name
    end
  end


end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    page = params[:page] ? params[:page] : 1
    @places = Place.paginate(per_page: 50, page: page)
    @places = @places.where(["name ILIKE ?", "%#{params[:search]}%"]) if params[:search].present?
  end

  def show
    @place = Place.find(params[:id])
    @location = @place.location

  end

  def place_map
    @place = Place.find(params[:id])

    # the hash holds all the markers for the map
    @place_hash = Gmaps4rails.build_markers(@place) do |place, marker|
      marker.lat place.location.lat
      marker.lng place.location.lng
      name = place.name.present? ? place.name : ''
      marker.infowindow '<a class="iwlayout" href=' + place_path(place) + '>' + name + '</a>'
    end

  end

end

app/views/places/index.html.erb
<div class="panel top-margin-sap" style="padding-bottom: 0px; padding-right: 5px" >
  <p class="search-text" style="font-size: 1.4em; display: inline">Search All Places</p>&nbsp;&nbsp;
  <p style="font-size: 1.1em; display: inline"> <%= link_to "(or just My Places)", my_savedplaces_path %></p>
  <div class="container left-margin-zero-sap">
    <div class="row" style="padding-top: 5px">

        <%= form_tag nil, method: :get do %>
          <%= text_field_tag :search, params[:search], placeholder: "Enter Place Title" %>&nbsp;
          <%= submit_tag 'Search', class: 'btn btn-sm btn-primary' %>
        <% end %>
        <p style="font-size: .8em; line-height: 80%">&nbsp;<%= link_to 'clear search', places_path %></p>

    </div>
  </div>
</div>

<%= will_paginate @places %>
	<div class="panel">
	  <% @places.each do |place| %>
	    <h4 style="display:inline; line-height: 1.5; font-family: 'Roboto Condensed'">
	        <%= link_to place.full_name, place_path(place) %></h4>&nbsp;&nbsp;&nbsp;
			<% if place.location.try(:city) && place.location.try(:state) %>
			     <p class="text-muted" style="display:inline"><%= place.location.city %>, <%= place.location.state %></p><br>
			<% end %>
	  <% end %>
	</div>
<%= will_paginate(@places) %>

app/views/places/place_map.html.erb
<h4 class="top-margin-map-sap" >Map for this Place</h4>

<!--style to fix google map zoom display-->
<style>
	.gm-style img { max-width: none; }
	.gm-style label { width: auto; display: inline; }
</style>

<div class="map_container">
  <div id="map_canvas" class="map_canvas"></div>
</div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({
						provider: { maxZoom: 15 },
						internal: {id: 'map_canvas'}
					},
					function(){
						markers = handler.addMarkers(<%=raw @place_hash.to_json %>);
						handler.bounds.extendWith(markers);
						handler.fitMapToBounds();
					});
</script>

app/views/places/show.html.erb
<div class="panel top-margin-sap right-padding-zero-sap" >
  <div style="font-size: 18px; font-weight: 500">
		<% @place_url = @place.urls.where(url_type: 'Owner').pluck("full_url") %>
		<% @place_url = @place.urls.where(url_type: 'Owner').pluck("full_url") %>
	  <p><%= link_to @place.name, @place_url[0], target: '_blank' %>&nbsp;&nbsp;
	    <a href=<%= @place.urls.first.full_url %>  target="_blank" >
	      <span class="glyphicon glyphicon-globe"></span>
	    </a>
	  </p>
	</div>

  <div class="container" style="margin-left: -15px">
    <div class="row" style="padding-bottom: 6px; font-weight: 300">
      <div class="col-lg-6 col-md-8 col-sm-9 col-xs-12">

        <% if @place.try(:description) %>
          <%= @place.description %><br>
	      <% else %>
	        <p style="color: #D9D9D9; display: inline">(no description)</p>
	      <% end %>

				<div style="font-weight: 500; line-height:2.2em" >
				  <% if @location %>
				    <%= @location.address1 %>&nbsp;&nbsp;
				    <%= @location.city %>,&nbsp;
				    <%= @location.state %>&nbsp;&nbsp;
				    <% if @location.zip_code %>
				      <%= @location.zip_code.postal_code %>&nbsp;&nbsp;
			      <% end %>
				    <%= link_to "Map View", place_map_path(@place), class: 'btn btn-info btn-sm' %>
					<% else %>
				    <p style="color: #D9D9D9; display: inline">(no address)</p>
					<% end %>
				</div>

			</div>
		</div>
	</div>

  <div class="container" style="margin-left: -15px">
    <div class="row" style="padding-bottom: 6px">
      <div class="col-xs-2 col-sm-1 col-md-1">
        Category
      </div>
      <div class="col-xs-10 col-sm-11 col-md-11">
        <% if @place.place_categories.count > 0 %>
          <ul style="padding-left: 20px;">
            <% @place.place_categories.each do |category| %>

              <% category_str = @place.place_categories.first.parent_id.nil? ? nil : PlaceCategory.find(@place.place_categories.first.parent_id).name %>
              <% subcategory_str = @place.place_categories.first.parent_id.nil? ? nil : @place.place_categories.first.name %>

              <li><%=  category_str.nil? ? subcategory_str : category_str + ' / ' + subcategory_str %></li>
            <% end %>
          </ul>
        <% else %>
          <p style="color: #D9D9D9; display: inline">(no category)</p>
        <% end %>
      </div>
    </div>
  </div>

</div>

<% story_count = @place.stories.where(ready_for_display: true).count %>
<% if story_count != 0 %>
	<div class="panel right-padding-zero-sap">
	  <h4>Read about this Place in <%= pluralize(story_count, 'Story') %></h4>
	  <ul style="padding-left: 20px;">
	    <% @place.stories.where(ready_for_display: true).each do |story| %>
	      <li style="display: inline; line-height: 2em" >
	      <% if user_signed_in? %>
	        <% @saved_story_count = Usersavedstory.where(story_id: story, user_id: current_user.id.to_i).count %>
	        <% if @saved_story_count < 1 %>
	          <p style="display: inline"><%= link_to 'Save Story', save_story_show_path(story),
                           class: 'btn btn-success btn-xs', style: 'padding: 2px 9px' %>&nbsp;</p> </li>
	        <% else %>
	          <p style="display: inline"><%= link_to 'Forget Story', forget_story_show_path(story),
                           class: 'btn btn-danger btn-xs', style: 'padding: 2px 5px' %>&nbsp;</p> </li>
	        <% end %>
	      <% end %>&nbsp;&nbsp;
	      <%= link_to story.title, story_path(story) %><br>

	    <% end %>
	  </ul>
	</div>
<% end %>

<% place_cnt = @place.urls.count %>
<div class="panel">
	<h4>External <%= "Link".pluralize(place_cnt) %> for this Place </h4>
	  <ul style="padding-left: 20px;">
	    <% @place.urls.each do |url| %>
	      <li><%= link_to (url.url_type = 'Owner' ? 'Business Website' : url.url_type), url.full_url, target: '_blank' %></li>
	    <% end %>
	  </ul>
</div>

<%= link_to 'Back to Places Index', places_path %>